// packages/solidjs/src/context/rattus-context.tsx
import type { RattusOrmInstallerOptions } from '@rattus-orm/core'
import type { RattusContext as RattusContextCore } from '@rattus-orm/core/utils/rattus-context'
import { createRattusContext } from '@rattus-orm/core/utils/rattus-context'
import type { ParentProps } from 'solid-js'
import { createContext } from 'solid-js'

import { SolidjsDataProvider } from '../data-provider/solidjs-data-provider'

export const RattusContext = createContext<Partial<RattusContextCore>>({ $database: undefined, $databases: undefined })

export function RattusProvider(props: ParentProps<RattusOrmInstallerOptions>) {
  const rattusContext = createRattusContext(props, new SolidjsDataProvider())

  return <RattusContext.Provider value={rattusContext}>{props.children}</RattusContext.Provider>
}

// packages/react-redux/src/context/rattus-context.tsx
import type { RattusContext as RattusContextCore } from '@rattus-orm/core/rattus-context'
import { createRattusContext } from '@rattus-orm/core/rattus-context'
import type { RattusOrmInstallerOptions } from '@rattus-orm/utils/sharedTypes'
import React, { createContext, type PropsWithChildren, useRef } from 'react'
import { Provider } from 'react-redux'
import type { Reducer, Store } from 'redux'

import { ReactReduxDataProvider } from '../data-provider/react-redux-data-provider'

type RattusProviderProps = RattusOrmInstallerOptions & {
  store: Store
  sideReducers?: Record<string, Reducer>
}

export const RattusContext = createContext<Partial<RattusContextCore>>({ $database: undefined, $databases: undefined })

export function RattusProvider(props: PropsWithChildren<RattusProviderProps>) {
  const rattusContext = useRef(createRattusContext(props, new ReactReduxDataProvider(props.store, props.sideReducers)))

  return (
    <RattusContext.Provider value={rattusContext.current}>
      <Provider store={props.store}>{props.children}</Provider>
    </RattusContext.Provider>
  )
}
